param(
    [string]$IndexPath = "work\index\functions_index.csv",
    [string]$ObjectRoot = "work\compile\ghidra",
    [string]$OutputPath = "work\link\partial\register_functions.partial.cpp",
    [string]$MissingStubsPath = "work\link\partial\missing_functions.partial.cpp"
)

$ErrorActionPreference = "Stop"

if (!(Test-Path $IndexPath)) {
    throw "Function index not found: $IndexPath"
}
if (!(Test-Path $ObjectRoot)) {
    throw "Object root not found: $ObjectRoot"
}

New-Item -ItemType Directory -Force -Path (Split-Path $OutputPath -Parent) | Out-Null

$rows = Import-Csv $IndexPath
$registered = New-Object System.Collections.Generic.List[object]
$missing = New-Object System.Collections.Generic.List[object]
$aliases = New-Object System.Collections.Generic.List[object]
$aliasKeys = New-Object "System.Collections.Generic.HashSet[string]"

function Add-InternalAlias([string]$Address, [string]$Symbol, [string]$OwnerAddress, [string]$Batch, [string]$Source, [string]$Kind) {
    $normalizedAddress = "0x{0}" -f ($Address -replace '^0x', '').ToLowerInvariant()
    $normalizedOwner = "0x{0}" -f ($OwnerAddress -replace '^0x', '').ToLowerInvariant()
    if ($normalizedAddress -eq $normalizedOwner) {
        return
    }

    $key = "$normalizedAddress|$Symbol"
    if (!$script:aliasKeys.Add($key)) {
        return
    }

    $script:aliases.Add([pscustomobject]@{
        Address = $normalizedAddress
        Symbol = $Symbol
        OwnerAddress = $normalizedOwner
        Batch = $Batch
        Source = $Source
        Kind = $Kind
    })
}

foreach ($row in $rows) {
    if ([string]::IsNullOrWhiteSpace($row.CppFile)) {
        continue
    }

    $symbol = [IO.Path]::GetFileNameWithoutExtension($row.CppFile)
    $objPath = Join-Path $ObjectRoot (Join-Path $row.Batch "obj\$symbol.o")
    if (Test-Path $objPath) {
        $registered.Add([pscustomobject]@{
            Address = $row.Start
            Symbol = $symbol
            Batch = $row.Batch
            Object = $objPath
        })

        $sourcePath = Join-Path "." $row.CppFile
        if (Test-Path $sourcePath) {
            Select-String -Path $sourcePath -Pattern 'case\s+0x([0-9a-fA-F]+)u:\s+goto\s+label_' | ForEach-Object {
                foreach ($match in $_.Matches) {
                    Add-InternalAlias `
                        -Address $match.Groups[1].Value `
                        -Symbol $symbol `
                        -OwnerAddress $row.Start `
                        -Batch $row.Batch `
                        -Source $row.CppFile `
                        -Kind "switch-case"
                }
            }

        }
    }
    else {
        $missing.Add([pscustomobject]@{
            Address = $row.Start
            Symbol = $symbol
            Batch = $row.Batch
            Object = $objPath
        })
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('#include "ps2_runtime.h"')
$lines.Add('#include "register_functions.h"')
$lines.Add("")
$lines.Add("// Auto-generated by tools\Generate-PartialRegister.ps1")
$lines.Add("// Registers only functions with compiled object files under work\compile\ghidra.")
$lines.Add("")

foreach ($item in $registered) {
    $lines.Add("void $($item.Symbol)(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime);")
}

$lines.Add("")
$lines.Add("void registerAllFunctions(PS2Runtime& runtime)")
$lines.Add("{")
foreach ($item in $registered) {
    $addr = $item.Address.ToLowerInvariant()
    $lines.Add("    runtime.registerFunction($($addr)u, $($item.Symbol));")
}
foreach ($item in $aliases) {
    $addr = $item.Address.ToLowerInvariant()
    $lines.Add("    runtime.registerFunction($($addr)u, $($item.Symbol));")
}
$lines.Add("}")

$lines | Set-Content -Path $OutputPath -Encoding ASCII

$manifestPath = [IO.Path]::ChangeExtension($OutputPath, ".manifest.csv")
$registered | Export-Csv -Path $manifestPath -NoTypeInformation

$aliasManifestPath = $OutputPath -replace '\.cpp$', '.aliases.csv'
$aliases | Export-Csv -Path $aliasManifestPath -NoTypeInformation

$stubLines = New-Object System.Collections.Generic.List[string]
$stubLines.Add('#include "ps2_runtime.h"')
$stubLines.Add("")
$stubLines.Add("#include <iostream>")
$stubLines.Add("")
$stubLines.Add("// Auto-generated by tools\Generate-PartialRegister.ps1")
$stubLines.Add("// Temporary link stubs for generated functions that have not been compiled yet.")
$stubLines.Add("// These make partial executables linkable; reaching one at runtime is still a missing-code blocker.")
$stubLines.Add("")
foreach ($item in $missing) {
    $addr = $item.Address.ToLowerInvariant()
    $stubLines.Add("void $($item.Symbol)(uint8_t*, R5900Context* ctx, PS2Runtime* runtime)")
    $stubLines.Add("{")
    $stubLines.Add("    static bool logged = false;")
    $stubLines.Add("    if (!logged) {")
    $stubLines.Add("        std::cerr << ""[partial-runner:missing-function] $($item.Symbol) @ $addr"" << std::endl;")
    $stubLines.Add("        logged = true;")
    $stubLines.Add("    }")
    $stubLines.Add("    if (ctx) {")
    $stubLines.Add("        ctx->pc = 0;")
    $stubLines.Add("    }")
    $stubLines.Add("    if (runtime) {")
    $stubLines.Add("        runtime->requestStop();")
    $stubLines.Add("    }")
    $stubLines.Add("}")
    $stubLines.Add("")
}
$stubLines | Set-Content -Path $MissingStubsPath -Encoding ASCII

$missingManifestPath = [IO.Path]::ChangeExtension($MissingStubsPath, ".manifest.csv")
$missing | Export-Csv -Path $missingManifestPath -NoTypeInformation

Write-Host "[OK] Partial register source: $OutputPath"
Write-Host "[OK] Partial register manifest: $manifestPath"
Write-Host "[OK] Registered functions: $($registered.Count)"
Write-Host "[OK] Internal PC aliases: $($aliases.Count)"
Write-Host "[OK] Alias manifest: $aliasManifestPath"
Write-Host "[OK] Missing stub source: $MissingStubsPath"
Write-Host "[OK] Missing stub manifest: $missingManifestPath"
Write-Host "[OK] Missing stub functions: $($missing.Count)"
